const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
const PurchaseBatch = require('../models/PurchaseBatch');
const Request = require('../models/Request');

/**
 * Procurement Service
 * Handles PDF generation and purchase tracking for manual book procurement workflow
 */

// Ensure upload directory exists
const UPLOAD_DIR = path.join(__dirname, '../uploads/procurement');
if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
}

/**
 * Generate procurement PDF
 * @param {Array} selectedBooks - Array of selected book objects with requestId, bookIndex, bookTitle, etc.
 * @param {String} adminName - Name/ID of admin generating the PDF
 * @returns {Object} { pdfPath, pdfFileName, pdfUrl }
 */
async function generateProcurementPDF(selectedBooks, adminName) {
  if (!selectedBooks || selectedBooks.length === 0) {
    throw new Error('No books selected for procurement');
  }

  try {
    // Generate unique batch ID and filename
    const batchId = uuidv4();
    const dateStr = new Date().toISOString().split('T')[0].replace(/-/g, '_');
    const pdfFileName = `PROCUREMENT_${dateStr}.pdf`;
    const pdfPath = path.join(UPLOAD_DIR, pdfFileName);

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margin: 40,
    });

    // Pipe to file
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);

    // Header with SVGA logo info (text-based)
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('SVGA BOOK BANK', { align: 'center' })
      .fontSize(12)
      .font('Helvetica')
      .text('Manual Book Procurement List', { align: 'center' })
      .moveDown(0.5);

    // Horizontal line
    doc
      .moveTo(40, doc.y)
      .lineTo(555, doc.y)
      .stroke();
    doc.moveDown(0.5);

    // Metadata section
    doc.fontSize(10).font('Helvetica-Bold');
    const now = new Date();
    const dateFormatted = now.toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
    const timeFormatted = now.toLocaleTimeString('en-IN');

    doc
      .text(`Generated Date: ${dateFormatted}`, { width: 250 })
      .text(`Generated Time: ${timeFormatted}`, { width: 250 });
    doc.fontSize(9).font('Helvetica');
    doc.text(`Generated By: ${adminName}`);
    doc.text(`Batch ID: ${batchId}`);
    doc.text(`Total Books: ${selectedBooks.length}`);
    doc.moveDown(0.5);

    // Horizontal line
    doc
      .moveTo(40, doc.y)
      .lineTo(555, doc.y)
      .stroke();
    doc.moveDown(0.5);

    // Table header
    doc.fontSize(9).font('Helvetica-Bold');
    const colPositions = {
      num: 40,
      title: 80,
      author: 210,
      publisher: 310,
      student: 420,
      studentId: 500,
    };
    const colWidths = {
      num: 35,
      title: 125,
      author: 95,
      publisher: 105,
      student: 75,
      studentId: 55,
    };

    // Draw header row
    doc.fillColor('#FFFFFF').rect(40, doc.y, 515, 20).fill('#0c2340');
    doc.fillColor('#FFFFFF');
    doc.text('No.', colPositions.num, doc.y + 4, { width: colWidths.num });
    doc.text('Book Name', colPositions.title, doc.y - 16, { width: colWidths.title });
    doc.text('Author', colPositions.author, doc.y - 16, { width: colWidths.author });
    doc.text('Publisher', colPositions.publisher, doc.y - 16, {
      width: colWidths.publisher,
    });
    doc.text('Student', colPositions.student, doc.y - 16, { width: colWidths.student });
    doc.text('Student ID', colPositions.studentId, doc.y - 16, {
      width: colWidths.studentId,
    });
    doc.moveDown(0.7);

    // Reset color for body
    doc.fillColor('#000000');

    // Table body
    doc.fontSize(8).font('Helvetica');
    let rowNum = 1;
    let currentY = doc.y;

    selectedBooks.forEach((book, index) => {
      // Check if we need a new page
      if (doc.y > 700) {
        doc.addPage();
        currentY = 40;
        doc.y = currentY;

        // Redraw header on new page
        doc.fontSize(9).font('Helvetica-Bold');
        doc.fillColor('#FFFFFF').rect(40, doc.y, 515, 20).fill('#0c2340');
        doc.fillColor('#FFFFFF');
        doc.text('No.', colPositions.num, doc.y + 4, { width: colWidths.num });
        doc.text('Book Name', colPositions.title, doc.y - 16, {
          width: colWidths.title,
        });
        doc.text('Author', colPositions.author, doc.y - 16, { width: colWidths.author });
        doc.text('Publisher', colPositions.publisher, doc.y - 16, {
          width: colWidths.publisher,
        });
        doc.text('Student', colPositions.student, doc.y - 16, {
          width: colWidths.student,
        });
        doc.text('Student ID', colPositions.studentId, doc.y - 16, {
          width: colWidths.studentId,
        });
        doc.moveDown(0.7);
        doc.fontSize(8).font('Helvetica');
        doc.fillColor('#000000');
      }

      // Draw row
      const rowY = doc.y;
      doc.text(rowNum.toString(), colPositions.num, rowY, { width: colWidths.num });
      doc.text(
        (book.bookTitle || 'N/A').substring(0, 20),
        colPositions.title,
        rowY,
        { width: colWidths.title }
      );
      doc.text(
        (book.author || 'N/A').substring(0, 15),
        colPositions.author,
        rowY,
        { width: colWidths.author }
      );
      doc.text(
        (book.publisher || 'N/A').substring(0, 15),
        colPositions.publisher,
        rowY,
        { width: colWidths.publisher }
      );
      doc.text(
        (book.studentName || 'N/A').substring(0, 10),
        colPositions.student,
        rowY,
        { width: colWidths.student }
      );
      doc.text(
        (book.studentId || 'N/A').substring(0, 8),
        colPositions.studentId,
        rowY,
        { width: colWidths.studentId }
      );
      doc.moveDown(0.5);
      rowNum++;
    });

    // Footer
    doc.moveDown(1);
    doc
      .moveTo(40, doc.y)
      .lineTo(555, doc.y)
      .stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).font('Helvetica').fillColor('#666666');
    doc.text(
      `Generated by SVGA Book Bank System - ${new Date().getFullYear()}`,
      { align: 'center' }
    );
    doc.text('This is a system-generated document', { align: 'center' });

    // Page numbering
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .text(`Page ${i + 1} of ${pageCount}`, 40, 740, { align: 'right' });
    }

    // Finalize PDF
    return new Promise((resolve, reject) => {
      stream.on('finish', () => {
        resolve({
          batchId,
          pdfPath,
          pdfFileName,
          pdfUrl: `/uploads/procurement/${pdfFileName}`,
          generatedAt: now,
        });
      });
      stream.on('error', reject);
      doc.end();
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error(`PDF generation failed: ${error.message}`);
  }
}

/**
 * Create procurement batch and update request books
 * @param {Array} selectedBooks - Array of selected books with requestId, bookIndex
 * @param {String} pdfPath - Path to generated PDF file
 * @param {String} pdfFileName - Name of PDF file
 * @param {String} pdfUrl - URL to access PDF
 * @param {String} batchId - Batch ID
 * @param {String} adminName - Admin name/ID
 */
async function createProcurementBatch(
  selectedBooks,
  pdfPath,
  pdfFileName,
  pdfUrl,
  batchId,
  adminName
) {
  try {
    // Extract unique request IDs
    const requestIds = [...new Set(selectedBooks.map((b) => b.requestId))];

    // Create batch record
    const batch = new PurchaseBatch({
      purchaseBatchId: batchId,
      generatedBy: adminName,
      totalBooks: selectedBooks.length,
      books: selectedBooks,
      pdfUrl,
      pdfFileName,
      requestIds,
    });
    await batch.save();

    // Update all affected requests
    for (const book of selectedBooks) {
      await Request.updateOne(
        {
          _id: book.requestId,
        },
        {
          $set: {
            [`requestedBooks.${book.bookIndex}.isPurchased`]: true,
            [`requestedBooks.${book.bookIndex}.purchasedAt`]: new Date(),
            [`requestedBooks.${book.bookIndex}.purchaseBatchId`]: batchId,
            [`requestedBooks.${book.bookIndex}.purchasePdfUrl`]: pdfUrl,
          },
        }
      );
    }

    return batch;
  } catch (error) {
    console.error('Error creating procurement batch:', error);
    // Clean up PDF if batch creation fails
    try {
      if (fs.existsSync(pdfPath)) {
        fs.unlinkSync(pdfPath);
      }
    } catch (cleanupErr) {
      console.error('Error cleaning up PDF:', cleanupErr);
    }
    throw new Error(`Batch creation failed: ${error.message}`);
  }
}

/**
 * Get procurement history
 * @param {Object} options - Query options { limit, skip, adminName }
 */
async function getProcurementHistory(options = {}) {
  try {
    const { limit = 50, skip = 0, adminName } = options;
    const query = adminName ? { generatedBy: adminName } : {};

    const batches = await PurchaseBatch.find(query)
      .sort({ generatedDate: -1 })
      .limit(limit)
      .skip(skip);

    const total = await PurchaseBatch.countDocuments(query);

    return {
      batches,
      total,
      limit,
      skip,
      hasMore: skip + limit < total,
    };
  } catch (error) {
    console.error('Error fetching procurement history:', error);
    throw new Error(`Failed to fetch history: ${error.message}`);
  }
}

/**
 * Get procurement batch details
 * @param {String} batchId - Batch ID
 */
async function getProcurementBatchDetails(batchId) {
  try {
    const batch = await PurchaseBatch.findOne({ purchaseBatchId: batchId });
    if (!batch) {
      throw new Error('Batch not found');
    }
    return batch;
  } catch (error) {
    console.error('Error fetching batch details:', error);
    throw new Error(`Failed to fetch batch: ${error.message}`);
  }
}

/**
 * Get books pending purchase (not yet purchased)
 * Typically used by admin to see which manual books need procurement
 */
async function getBooksPendingPurchase() {
  try {
    const requests = await Request.find({
      requestedBooks: {
        $elemMatch: {
          decision: 'Approved',
          isPurchased: false,
        },
      },
    });

    const pendingBooks = [];
    requests.forEach((req) => {
      req.requestedBooks.forEach((book, index) => {
        if (book.decision === 'Approved' && !book.isPurchased) {
          pendingBooks.push({
            requestId: req._id,
            bookIndex: index,
            bookTitle: book.title,
            author: book.author,
            publisher: book.publisher,
            edition: book.edition,
            studentName: req.studentName,
            studentId: req.studentId,
            studentEmail: req.studentEmail,
          });
        }
      });
    });

    return pendingBooks;
  } catch (error) {
    console.error('Error fetching pending books:', error);
    throw new Error(`Failed to fetch pending books: ${error.message}`);
  }
}

module.exports = {
  generateProcurementPDF,
  createProcurementBatch,
  getProcurementHistory,
  getProcurementBatchDetails,
  getBooksPendingPurchase,
};
